-- Seed remaining world countries (non-African)
-- Africa was seeded in 20260222210000

BEGIN;

INSERT INTO public.countries (id, name, iso_code, iso3_code, capital, currency_code, phone_code, is_active)
VALUES
  -- Asia
  (gen_random_uuid(), 'Afghanistan', 'AF', 'AFG', 'Kabul', 'AFN', '+93', true),
  (gen_random_uuid(), 'Armenia', 'AM', 'ARM', 'Yerevan', 'AMD', '+374', true),
  (gen_random_uuid(), 'Azerbaijan', 'AZ', 'AZE', 'Baku', 'AZN', '+994', true),
  (gen_random_uuid(), 'Bahrain', 'BH', 'BHR', 'Manama', 'BHD', '+973', true),
  (gen_random_uuid(), 'Bangladesh', 'BD', 'BGD', 'Dhaka', 'BDT', '+880', true),
  (gen_random_uuid(), 'Bhutan', 'BT', 'BTN', 'Thimphu', 'BTN', '+975', true),
  (gen_random_uuid(), 'Brunei', 'BN', 'BRN', 'Bandar Seri Begawan', 'BND', '+673', true),
  (gen_random_uuid(), 'Cambodia', 'KH', 'KHM', 'Phnom Penh', 'KHR', '+855', true),
  (gen_random_uuid(), 'China', 'CN', 'CHN', 'Beijing', 'CNY', '+86', true),
  (gen_random_uuid(), 'Georgia', 'GE', 'GEO', 'Tbilisi', 'GEL', '+995', true),
  (gen_random_uuid(), 'India', 'IN', 'IND', 'New Delhi', 'INR', '+91', true),
  (gen_random_uuid(), 'Indonesia', 'ID', 'IDN', 'Jakarta', 'IDR', '+62', true),
  (gen_random_uuid(), 'Iran', 'IR', 'IRN', 'Tehran', 'IRR', '+98', true),
  (gen_random_uuid(), 'Iraq', 'IQ', 'IRQ', 'Baghdad', 'IQD', '+964', true),
  (gen_random_uuid(), 'Israel', 'IL', 'ISR', 'Jerusalem', 'ILS', '+972', true),
  (gen_random_uuid(), 'Japan', 'JP', 'JPN', 'Tokyo', 'JPY', '+81', true),
  (gen_random_uuid(), 'Jordan', 'JO', 'JOR', 'Amman', 'JOD', '+962', true),
  (gen_random_uuid(), 'Kazakhstan', 'KZ', 'KAZ', 'Astana', 'KZT', '+7', true),
  (gen_random_uuid(), 'Kuwait', 'KW', 'KWT', 'Kuwait City', 'KWD', '+965', true),
  (gen_random_uuid(), 'Kyrgyzstan', 'KG', 'KGZ', 'Bishkek', 'KGS', '+996', true),
  (gen_random_uuid(), 'Laos', 'LA', 'LAO', 'Vientiane', 'LAK', '+856', true),
  (gen_random_uuid(), 'Lebanon', 'LB', 'LBN', 'Beirut', 'LBP', '+961', true),
  (gen_random_uuid(), 'Malaysia', 'MY', 'MYS', 'Kuala Lumpur', 'MYR', '+60', true),
  (gen_random_uuid(), 'Maldives', 'MV', 'MDV', 'Malé', 'MVR', '+960', true),
  (gen_random_uuid(), 'Mongolia', 'MN', 'MNG', 'Ulaanbaatar', 'MNT', '+976', true),
  (gen_random_uuid(), 'Myanmar', 'MM', 'MMR', 'Naypyidaw', 'MMK', '+95', true),
  (gen_random_uuid(), 'Nepal', 'NP', 'NPL', 'Kathmandu', 'NPR', '+977', true),
  (gen_random_uuid(), 'North Korea', 'KP', 'PRK', 'Pyongyang', 'KPW', '+850', true),
  (gen_random_uuid(), 'Oman', 'OM', 'OMN', 'Muscat', 'OMR', '+968', true),
  (gen_random_uuid(), 'Pakistan', 'PK', 'PAK', 'Islamabad', 'PKR', '+92', true),
  (gen_random_uuid(), 'Palestine', 'PS', 'PSE', 'Ramallah', 'ILS', '+970', true),
  (gen_random_uuid(), 'Philippines', 'PH', 'PHL', 'Manila', 'PHP', '+63', true),
  (gen_random_uuid(), 'Qatar', 'QA', 'QAT', 'Doha', 'QAR', '+974', true),
  (gen_random_uuid(), 'Saudi Arabia', 'SA', 'SAU', 'Riyadh', 'SAR', '+966', true),
  (gen_random_uuid(), 'Singapore', 'SG', 'SGP', 'Singapore', 'SGD', '+65', true),
  (gen_random_uuid(), 'South Korea', 'KR', 'KOR', 'Seoul', 'KRW', '+82', true),
  (gen_random_uuid(), 'Sri Lanka', 'LK', 'LKA', 'Sri Jayawardenepura Kotte', 'LKR', '+94', true),
  (gen_random_uuid(), 'Syria', 'SY', 'SYR', 'Damascus', 'SYP', '+963', true),
  (gen_random_uuid(), 'Taiwan', 'TW', 'TWN', 'Taipei', 'TWD', '+886', true),
  (gen_random_uuid(), 'Tajikistan', 'TJ', 'TJK', 'Dushanbe', 'TJS', '+992', true),
  (gen_random_uuid(), 'Thailand', 'TH', 'THA', 'Bangkok', 'THB', '+66', true),
  (gen_random_uuid(), 'Timor-Leste', 'TL', 'TLS', 'Dili', 'USD', '+670', true),
  (gen_random_uuid(), 'Turkey', 'TR', 'TUR', 'Ankara', 'TRY', '+90', true),
  (gen_random_uuid(), 'Turkmenistan', 'TM', 'TKM', 'Ashgabat', 'TMT', '+993', true),
  (gen_random_uuid(), 'United Arab Emirates', 'AE', 'ARE', 'Abu Dhabi', 'AED', '+971', true),
  (gen_random_uuid(), 'Uzbekistan', 'UZ', 'UZB', 'Tashkent', 'UZS', '+998', true),
  (gen_random_uuid(), 'Vietnam', 'VN', 'VNM', 'Hanoi', 'VND', '+84', true),
  (gen_random_uuid(), 'Yemen', 'YE', 'YEM', 'Sana''a', 'YER', '+967', true),

  -- Europe
  (gen_random_uuid(), 'Albania', 'AL', 'ALB', 'Tirana', 'ALL', '+355', true),
  (gen_random_uuid(), 'Andorra', 'AD', 'AND', 'Andorra la Vella', 'EUR', '+376', true),
  (gen_random_uuid(), 'Austria', 'AT', 'AUT', 'Vienna', 'EUR', '+43', true),
  (gen_random_uuid(), 'Belarus', 'BY', 'BLR', 'Minsk', 'BYN', '+375', true),
  (gen_random_uuid(), 'Belgium', 'BE', 'BEL', 'Brussels', 'EUR', '+32', true),
  (gen_random_uuid(), 'Bosnia and Herzegovina', 'BA', 'BIH', 'Sarajevo', 'BAM', '+387', true),
  (gen_random_uuid(), 'Bulgaria', 'BG', 'BGR', 'Sofia', 'BGN', '+359', true),
  (gen_random_uuid(), 'Croatia', 'HR', 'HRV', 'Zagreb', 'EUR', '+385', true),
  (gen_random_uuid(), 'Cyprus', 'CY', 'CYP', 'Nicosia', 'EUR', '+357', true),
  (gen_random_uuid(), 'Czech Republic', 'CZ', 'CZE', 'Prague', 'CZK', '+420', true),
  (gen_random_uuid(), 'Denmark', 'DK', 'DNK', 'Copenhagen', 'DKK', '+45', true),
  (gen_random_uuid(), 'Estonia', 'EE', 'EST', 'Tallinn', 'EUR', '+372', true),
  (gen_random_uuid(), 'Finland', 'FI', 'FIN', 'Helsinki', 'EUR', '+358', true),
  (gen_random_uuid(), 'France', 'FR', 'FRA', 'Paris', 'EUR', '+33', true),
  (gen_random_uuid(), 'Germany', 'DE', 'DEU', 'Berlin', 'EUR', '+49', true),
  (gen_random_uuid(), 'Greece', 'GR', 'GRC', 'Athens', 'EUR', '+30', true),
  (gen_random_uuid(), 'Hungary', 'HU', 'HUN', 'Budapest', 'HUF', '+36', true),
  (gen_random_uuid(), 'Iceland', 'IS', 'ISL', 'Reykjavik', 'ISK', '+354', true),
  (gen_random_uuid(), 'Ireland', 'IE', 'IRL', 'Dublin', 'EUR', '+353', true),
  (gen_random_uuid(), 'Italy', 'IT', 'ITA', 'Rome', 'EUR', '+39', true),
  (gen_random_uuid(), 'Kosovo', 'XK', 'XKX', 'Pristina', 'EUR', '+383', true),
  (gen_random_uuid(), 'Latvia', 'LV', 'LVA', 'Riga', 'EUR', '+371', true),
  (gen_random_uuid(), 'Liechtenstein', 'LI', 'LIE', 'Vaduz', 'CHF', '+423', true),
  (gen_random_uuid(), 'Lithuania', 'LT', 'LTU', 'Vilnius', 'EUR', '+370', true),
  (gen_random_uuid(), 'Luxembourg', 'LU', 'LUX', 'Luxembourg', 'EUR', '+352', true),
  (gen_random_uuid(), 'Malta', 'MT', 'MLT', 'Valletta', 'EUR', '+356', true),
  (gen_random_uuid(), 'Moldova', 'MD', 'MDA', 'Chișinău', 'MDL', '+373', true),
  (gen_random_uuid(), 'Monaco', 'MC', 'MCO', 'Monaco', 'EUR', '+377', true),
  (gen_random_uuid(), 'Montenegro', 'ME', 'MNE', 'Podgorica', 'EUR', '+382', true),
  (gen_random_uuid(), 'Netherlands', 'NL', 'NLD', 'Amsterdam', 'EUR', '+31', true),
  (gen_random_uuid(), 'North Macedonia', 'MK', 'MKD', 'Skopje', 'MKD', '+389', true),
  (gen_random_uuid(), 'Norway', 'NO', 'NOR', 'Oslo', 'NOK', '+47', true),
  (gen_random_uuid(), 'Poland', 'PL', 'POL', 'Warsaw', 'PLN', '+48', true),
  (gen_random_uuid(), 'Portugal', 'PT', 'PRT', 'Lisbon', 'EUR', '+351', true),
  (gen_random_uuid(), 'Romania', 'RO', 'ROU', 'Bucharest', 'RON', '+40', true),
  (gen_random_uuid(), 'Russia', 'RU', 'RUS', 'Moscow', 'RUB', '+7', true),
  (gen_random_uuid(), 'San Marino', 'SM', 'SMR', 'San Marino', 'EUR', '+378', true),
  (gen_random_uuid(), 'Serbia', 'RS', 'SRB', 'Belgrade', 'RSD', '+381', true),
  (gen_random_uuid(), 'Slovakia', 'SK', 'SVK', 'Bratislava', 'EUR', '+421', true),
  (gen_random_uuid(), 'Slovenia', 'SI', 'SVN', 'Ljubljana', 'EUR', '+386', true),
  (gen_random_uuid(), 'Spain', 'ES', 'ESP', 'Madrid', 'EUR', '+34', true),
  (gen_random_uuid(), 'Sweden', 'SE', 'SWE', 'Stockholm', 'SEK', '+46', true),
  (gen_random_uuid(), 'Switzerland', 'CH', 'CHE', 'Bern', 'CHF', '+41', true),
  (gen_random_uuid(), 'Ukraine', 'UA', 'UKR', 'Kyiv', 'UAH', '+380', true),
  (gen_random_uuid(), 'United Kingdom', 'GB', 'GBR', 'London', 'GBP', '+44', true),
  (gen_random_uuid(), 'Vatican City', 'VA', 'VAT', 'Vatican City', 'EUR', '+39', true),

  -- North America
  (gen_random_uuid(), 'Antigua and Barbuda', 'AG', 'ATG', 'St. John''s', 'XCD', '+1-268', true),
  (gen_random_uuid(), 'Bahamas', 'BS', 'BHS', 'Nassau', 'BSD', '+1-242', true),
  (gen_random_uuid(), 'Barbados', 'BB', 'BRB', 'Bridgetown', 'BBD', '+1-246', true),
  (gen_random_uuid(), 'Belize', 'BZ', 'BLZ', 'Belmopan', 'BZD', '+501', true),
  (gen_random_uuid(), 'Canada', 'CA', 'CAN', 'Ottawa', 'CAD', '+1', true),
  (gen_random_uuid(), 'Costa Rica', 'CR', 'CRI', 'San José', 'CRC', '+506', true),
  (gen_random_uuid(), 'Cuba', 'CU', 'CUB', 'Havana', 'CUP', '+53', true),
  (gen_random_uuid(), 'Dominica', 'DM', 'DMA', 'Roseau', 'XCD', '+1-767', true),
  (gen_random_uuid(), 'Dominican Republic', 'DO', 'DOM', 'Santo Domingo', 'DOP', '+1-809', true),
  (gen_random_uuid(), 'El Salvador', 'SV', 'SLV', 'San Salvador', 'USD', '+503', true),
  (gen_random_uuid(), 'Grenada', 'GD', 'GRD', 'St. George''s', 'XCD', '+1-473', true),
  (gen_random_uuid(), 'Guatemala', 'GT', 'GTM', 'Guatemala City', 'GTQ', '+502', true),
  (gen_random_uuid(), 'Haiti', 'HT', 'HTI', 'Port-au-Prince', 'HTG', '+509', true),
  (gen_random_uuid(), 'Honduras', 'HN', 'HND', 'Tegucigalpa', 'HNL', '+504', true),
  (gen_random_uuid(), 'Jamaica', 'JM', 'JAM', 'Kingston', 'JMD', '+1-876', true),
  (gen_random_uuid(), 'Mexico', 'MX', 'MEX', 'Mexico City', 'MXN', '+52', true),
  (gen_random_uuid(), 'Nicaragua', 'NI', 'NIC', 'Managua', 'NIO', '+505', true),
  (gen_random_uuid(), 'Panama', 'PA', 'PAN', 'Panama City', 'PAB', '+507', true),
  (gen_random_uuid(), 'Saint Kitts and Nevis', 'KN', 'KNA', 'Basseterre', 'XCD', '+1-869', true),
  (gen_random_uuid(), 'Saint Lucia', 'LC', 'LCA', 'Castries', 'XCD', '+1-758', true),
  (gen_random_uuid(), 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'Kingstown', 'XCD', '+1-784', true),
  (gen_random_uuid(), 'Trinidad and Tobago', 'TT', 'TTO', 'Port of Spain', 'TTD', '+1-868', true),
  (gen_random_uuid(), 'United States', 'US', 'USA', 'Washington, D.C.', 'USD', '+1', true),

  -- South America
  (gen_random_uuid(), 'Argentina', 'AR', 'ARG', 'Buenos Aires', 'ARS', '+54', true),
  (gen_random_uuid(), 'Bolivia', 'BO', 'BOL', 'Sucre', 'BOB', '+591', true),
  (gen_random_uuid(), 'Brazil', 'BR', 'BRA', 'Brasília', 'BRL', '+55', true),
  (gen_random_uuid(), 'Chile', 'CL', 'CHL', 'Santiago', 'CLP', '+56', true),
  (gen_random_uuid(), 'Colombia', 'CO', 'COL', 'Bogotá', 'COP', '+57', true),
  (gen_random_uuid(), 'Ecuador', 'EC', 'ECU', 'Quito', 'USD', '+593', true),
  (gen_random_uuid(), 'Guyana', 'GY', 'GUY', 'Georgetown', 'GYD', '+592', true),
  (gen_random_uuid(), 'Paraguay', 'PY', 'PRY', 'Asunción', 'PYG', '+595', true),
  (gen_random_uuid(), 'Peru', 'PE', 'PER', 'Lima', 'PEN', '+51', true),
  (gen_random_uuid(), 'Suriname', 'SR', 'SUR', 'Paramaribo', 'SRD', '+597', true),
  (gen_random_uuid(), 'Uruguay', 'UY', 'URY', 'Montevideo', 'UYU', '+598', true),
  (gen_random_uuid(), 'Venezuela', 'VE', 'VEN', 'Caracas', 'VES', '+58', true),

  -- Oceania
  (gen_random_uuid(), 'Australia', 'AU', 'AUS', 'Canberra', 'AUD', '+61', true),
  (gen_random_uuid(), 'Fiji', 'FJ', 'FJI', 'Suva', 'FJD', '+679', true),
  (gen_random_uuid(), 'Kiribati', 'KI', 'KIR', 'Tarawa', 'AUD', '+686', true),
  (gen_random_uuid(), 'Marshall Islands', 'MH', 'MHL', 'Majuro', 'USD', '+692', true),
  (gen_random_uuid(), 'Micronesia', 'FM', 'FSM', 'Palikir', 'USD', '+691', true),
  (gen_random_uuid(), 'Nauru', 'NR', 'NRU', 'Yaren', 'AUD', '+674', true),
  (gen_random_uuid(), 'New Zealand', 'NZ', 'NZL', 'Wellington', 'NZD', '+64', true),
  (gen_random_uuid(), 'Palau', 'PW', 'PLW', 'Ngerulmud', 'USD', '+680', true),
  (gen_random_uuid(), 'Papua New Guinea', 'PG', 'PNG', 'Port Moresby', 'PGK', '+675', true),
  (gen_random_uuid(), 'Samoa', 'WS', 'WSM', 'Apia', 'WST', '+685', true),
  (gen_random_uuid(), 'Solomon Islands', 'SB', 'SLB', 'Honiara', 'SBD', '+677', true),
  (gen_random_uuid(), 'Tonga', 'TO', 'TON', 'Nuku''alofa', 'TOP', '+676', true),
  (gen_random_uuid(), 'Tuvalu', 'TV', 'TUV', 'Funafuti', 'AUD', '+688', true),
  (gen_random_uuid(), 'Vanuatu', 'VU', 'VUT', 'Port Vila', 'VUV', '+678', true)
ON CONFLICT DO NOTHING;

COMMIT;
